In [1]:
pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in C:\anaconda3\Lib\site-packages (3.8.1)
Requirement already satisfied: click in C:\anaconda3\Lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in C:\anaconda3\Lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in C:\anaconda3\Lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in C:\anaconda3\Lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in C:\anaconda3\Lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [3]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

True

# Natural Language Processing
1) Natural language Understanding
2) Natural Language Generation

lets begin with NLU

# Step=1 tokenization
* sentence T.
* word T.

In [41]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

In [42]:
text="""Wikipedia[c] is a free online encyclopedia written and maintained by a community of volunteers, known as Wikipedians, through open collaboration and the wiki software MediaWiki. Founded by Jimmy Wales and Larry Sanger in 2001, Wikipedia has been hosted since 2003 by the Wikimedia Foundation, an American nonprofit organization funded mainly by donations from readers.[1] Wikipedia is the largest and most-read reference work in history.[2][3]"""

In [43]:
# classic python way
tokens=text.split()
tokens

['Wikipedia[c]',
 'is',
 'a',
 'free',
 'online',
 'encyclopedia',
 'written',
 'and',
 'maintained',
 'by',
 'a',
 'community',
 'of',
 'volunteers,',
 'known',
 'as',
 'Wikipedians,',
 'through',
 'open',
 'collaboration',
 'and',
 'the',
 'wiki',
 'software',
 'MediaWiki.',
 'Founded',
 'by',
 'Jimmy',
 'Wales',
 'and',
 'Larry',
 'Sanger',
 'in',
 '2001,',
 'Wikipedia',
 'has',
 'been',
 'hosted',
 'since',
 '2003',
 'by',
 'the',
 'Wikimedia',
 'Foundation,',
 'an',
 'American',
 'nonprofit',
 'organization',
 'funded',
 'mainly',
 'by',
 'donations',
 'from',
 'readers.[1]',
 'Wikipedia',
 'is',
 'the',
 'largest',
 'and',
 'most-read',
 'reference',
 'work',
 'in',
 'history.[2][3]']

In [44]:
words=word_tokenize(text)
words

['Wikipedia',
 '[',
 'c',
 ']',
 'is',
 'a',
 'free',
 'online',
 'encyclopedia',
 'written',
 'and',
 'maintained',
 'by',
 'a',
 'community',
 'of',
 'volunteers',
 ',',
 'known',
 'as',
 'Wikipedians',
 ',',
 'through',
 'open',
 'collaboration',
 'and',
 'the',
 'wiki',
 'software',
 'MediaWiki',
 '.',
 'Founded',
 'by',
 'Jimmy',
 'Wales',
 'and',
 'Larry',
 'Sanger',
 'in',
 '2001',
 ',',
 'Wikipedia',
 'has',
 'been',
 'hosted',
 'since',
 '2003',
 'by',
 'the',
 'Wikimedia',
 'Foundation',
 ',',
 'an',
 'American',
 'nonprofit',
 'organization',
 'funded',
 'mainly',
 'by',
 'donations',
 'from',
 'readers',
 '.',
 '[',
 '1',
 ']',
 'Wikipedia',
 'is',
 'the',
 'largest',
 'and',
 'most-read',
 'reference',
 'work',
 'in',
 'history',
 '.',
 '[',
 '2',
 ']',
 '[',
 '3',
 ']']

In [45]:
sente=sent_tokenize(text)
sente

['Wikipedia[c] is a free online encyclopedia written and maintained by a community of volunteers, known as Wikipedians, through open collaboration and the wiki software MediaWiki.',
 'Founded by Jimmy Wales and Larry Sanger in 2001, Wikipedia has been hosted since 2003 by the Wikimedia Foundation, an American nonprofit organization funded mainly by donations from readers.',
 '[1] Wikipedia is the largest and most-read reference work in history.',
 '[2][3]']

# Step 2= Discarding Stopwords

In [46]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\student\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [47]:
wiki_stopwords= stopwords.words('english')
print(len(wiki_stopwords))

198

In [48]:
print(wiki_stopwords)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

* Filter Words

In [49]:
filt_words= [x for x in words if x not in wiki_stopwords]
print(filt_words)

['Wikipedia', '[', 'c', ']', 'free', 'online', 'encyclopedia', 'written', 'maintained', 'community', 'volunteers', ',', 'known', 'Wikipedians', ',', 'open', 'collaboration', 'wiki', 'software', 'MediaWiki', '.', 'Founded', 'Jimmy', 'Wales', 'Larry', 'Sanger', '2001', ',', 'Wikipedia', 'hosted', 'since', '2003', 'Wikimedia', 'Foundation', ',', 'American', 'nonprofit', 'organization', 'funded', 'mainly', 'donations', 'readers', '.', '[', '1', ']', 'Wikipedia', 'largest', 'most-read', 'reference', 'work', 'history', '.', '[', '2', ']', '[', '3', ']']

In [54]:
# !python -m spacy download en_core_web_sm

In [55]:
%pip install SpaCy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: SpaCy in .\AppData\Roaming\Python\Python312\site-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (0.23.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in C:\anaconda3\Lib\site-packages (from SpaCy) (4.66.4)
Requirement already satisfied: numpy>=1.19.0 in .\AppData\Roaming\Python\Python312\site-packages (from SpaCy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in C:\anaconda3\Lib\site-packages (from SpaCy) (2.32.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in C:\anaconda3\Lib\site-packages (from SpaCy) (2.12.3)
Requirement already satisfied: jinja2 in C:\anaconda3\Lib\site-packages (from SpaCy) (3.1.4)
Requirement already satisfied: setuptools in C:\anaconda3\Lib\site-packages (from SpaCy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in C:\anaconda3\Lib\site-packages (from SpaCy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\anaconda3\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->SpaCy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.4 in C:\anaconda3\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->SpaCy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\anaconda3\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->SpaCy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\anaconda3\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->SpaCy) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->SpaCy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in C:\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->SpaCy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->SpaCy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in C:\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->SpaCy) (2025.10.5)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in .\AppData\Roaming\Python\Python312\site-packages (from thinc<8.4.0,>=8.3.4->SpaCy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in .\AppData\Roaming\Python\Python312\site-packages (from thinc<8.4.0,>=8.3.4->SpaCy) (0.1.5)
Requirement already satisfied: colorama in C:\anaconda3\Lib\site-packages (from tqdm<5.0.0,>=4.38.0->SpaCy) (0.4.6)
Requirement already satisfied: typer>=0.23.0 in .\AppData\Roaming\Python\Python312\site-packages (from typer-slim<1.0.0,>=0.3.0->SpaCy) (0.23.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in .\AppData\Roaming\Python\Python312\site-packages (from weasel<0.5.0,>=0.4.2->SpaCy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in C:\anaconda3\Lib\site-packages (from weasel<0.5.0,>=0.4.2->SpaCy) (5.2.1)
Requirement already satisfied: click>=8.0.0 in C:\anaconda3\Lib\site-packages (from typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->SpaCy) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in C:\anaconda3\Lib\site-packages (from typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->SpaCy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in C:\anaconda3\Lib\site-packages (from typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->SpaCy) (13.3.5)
Requirement already satisfied: annotated-doc>=0.0.2 in .\AppData\Roaming\Python\Python312\site-packages (from typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->SpaCy) (0.0.4)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in C:\anaconda3\Lib\site-packages (from rich>=10.11.0->typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->SpaCy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\anaconda3\Lib\site-packages (from rich>=10.11.0->typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->SpaCy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in C:\anaconda3\Lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->typer>=0.23.0->typer-slim<1.0.0,>=0.3.0->SpaCy) (0.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\anaconda3\Lib\site-packages (from jinja2->SpaCy) (2.1.3)
Note: you may need to restart the kernel to use updated packages.

In [56]:
import spacy
from collections import Counter
from string import punctuation

In [57]:
import en_core_web_sm
nlp = en_core_web_sm.load()

In [58]:
def get_hotwords(text):
    result =[]
    pos_tag =['PROPN','ADJ','NOUN']
    doc= nlp(text.lower())
    for token in doc:
        if (token.text in nlp.Defaults.stop_words or token.text in punctuation):
            continue
            if(token.pos_ in pos_tag):
                result.append(token.text)
    return result

In [59]:
aurora="An aurora pl. aurorae or auroras is a natural light display in Earths sky, predominantly observed in high-latitude regions around the Arctic and Antarctic. The terms northern lights (aurora borealis) and southern lights (aurora australis) are used in the Northern and Southern Hemispheres respectively.[3][c] Auroras display dynamic patterns of radiant light that appear as curtains, rays, spirals or dynamic flickers covering the entire sky"

In [60]:
get_hotwords(aurora)

[]

# Step3 = Stemming/ lemmatization

In [61]:
from nltk.stem import PorterStemmer
from nltk.stem.snowball import SnowballStemmer
ps = PorterStemmer()
words = ['jumped','daily','better','eating','captured','building']

In [62]:
for word in words:
    print(f"{word} => {ps.stem(word)}")

jumped => jump
daily => daili
better => better
eating => eat
captured => captur
building => build

In [63]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\student\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [64]:
lemma=WordNetLemmatizer()
for word in words:
    print(f"{word}=>{lemma.lemmatize(word,pos='v')}")

jumped=>jump
daily=>daily
better=>better
eating=>eat
captured=>capture
building=>build

# stemming vs Lemmatization
* stemming is faster than lemmatization
* stemming chops of words irrespective of context
* lemmatizer is context dependent has parts of speech relevancy dictonary based approach
* lemmatizer is more accurate than stemming

# step 4 Bag of words 
* (based on thie inputs provided by users)

In [80]:
sent=['This is the first piece of document loaded.',
     'this is second of same kind.',
     'this is third document',
     'whats this kind of then']
print(sent)

['This is the first piece of document loaded.', 'this is second of same kind.', 'this is third document', 'whats this kind of then']

In [81]:
import pandas as pd

In [82]:
from sklearn.feature_extraction.text import CountVectorizer
v= CountVectorizer()
X=v.fit_transform(sent)
columns=v.get_feature_names_out()
df=pd.DataFrame(X.toarray(),columns=columns,index=sent)
df

,document,first,is,kind,loaded,of,piece,same,second,the,then,third,this,whats
This is the first piece of document loaded.,1,1,1,0,1,1,1,0,0,1,0,0,1,0
this is second of same kind.,0,0,1,1,0,1,0,1,1,0,0,0,1,0
this is third document,1,0,1,0,0,0,0,0,0,0,0,1,1,0
whats this kind of then,0,0,0,1,0,1,0,0,0,0,1,0,1,1

In [84]:
print(v.vocabulary_)

{'this': 12, 'is': 2, 'the': 9, 'first': 1, 'piece': 6, 'of': 5, 'document': 0, 'loaded': 4, 'second': 8, 'same': 7, 'kind': 3, 'third': 11, 'whats': 13, 'then': 10}

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
Y=tfidf.fit_transform(sent)
df_tfidf = pd.DataFrame(Y.toarray(),columns=tfidf.get_feature_names_out(),index=sent)
df_tfidf

,document,first,is,kind,loaded,of,piece,same,second,the,then,third,this,whats
This is the first piece of document loaded.,0.329977,0.418533,0.267144,0.000000,0.418533,0.267144,0.418533,0.000000,0.000000,0.418533,0.000000,0.000000,0.218408,0.000000
this is second of same kind.,0.000000,0.000000,0.331439,0.409393,0.000000,0.331439,0.000000,0.519263,0.519263,0.000000,0.000000,0.000000,0.270973,0.000000
this is third document,0.519714,0.000000,0.420753,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.659191,0.343993,0.000000
whats this kind of then,0.000000,0.000000,0.000000,0.433919,0.000000,0.351295,0.000000,0.000000,0.000000,0.000000,0.550372,0.000000,0.287207,0.550372

* Emphasis is on important words
* Doesn't capture word similarity/context
* for a huge sentence results in sparse matrix
*

# NLG

# word2vec

* learning context and similarity
* need to tokenize and preprocess first
* doesnt fit for small data, or machine with low ROM

In [1]:
%pip install gensim

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gensim in C:\anaconda3\Lib\site-packages (4.3.2)
Requirement already satisfied: numpy>=1.18.5 in .\AppData\Roaming\Python\Python312\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in C:\anaconda3\Lib\site-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in C:\anaconda3\Lib\site-packages (from gensim) (5.2.1)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip install --upgrade gensim

In [5]:
import scipy
import gensim
print(f"SciPy version: {scipy.__version__}")
print(f"Gensim version: {gensim.__version__}")

from gensim.models import Word2Vec
print("Import successful!")

SciPy version: 1.13.1
Gensim version: 4.4.0
Import successful!

In [4]:
from gensim.models import Word2Vec

In [8]:
#mapping similarity index
new_words=['Ephemeral','Quixotic','Labyrinth','Mellifluous','Petrichor','Sonder','Effervescent','Serendipity','Incandescent','Nefarious']
model= Word2Vec([new_words],vector_size=20, window=5,min_count=1)
for x in new_words:
    print(f"{x}->{model.wv['Petrichor']}")

Ephemeral->[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Quixotic->[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Labyrinth->[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Mellifluous->[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Petrichor->[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Sonder->[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Effervescent->[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Serendipity->[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Incandescent->[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Nefarious->[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]

In [14]:
# using a pretrained llm
import gensim.downloader as api

In [15]:
new_model = api.load('glove-wiki-gigaword-100')

# Quick test: Find words similar to 'coding'
print(new_model.most_similar('coding'))

[==================================================] 100.0% 128.1/128.1MB downloaded
[('encoding', 0.714169979095459), ('decoding', 0.6445214152336121), ('algorithms', 0.623323917388916), ('transcription', 0.5700728893280029), ('algorithm', 0.5697765350341797), ('interface', 0.5659469366073608), ('rna', 0.5580451488494873), ('sequence', 0.5532592535018921), ('modulation', 0.5507382750511169), ('notation', 0.5438306927680969)]

In [22]:
print("Top most 7 words similar to word making:")
print(new_model.most_similar("making",topn=7),"\n")

Top most 7 words similar to word making:
[('make', 0.8685981035232544), ('made', 0.8520025610923767), ('well', 0.8188449740409851), ('taking', 0.8174976110458374), ('putting', 0.8130989074707031), ('instead', 0.8077840805053711), ('even', 0.8059568405151367)]